Repository mundipagg/opencart, pull requests merged in 2018-03, with the labels that each got.

#124 Checkout.js Update
  catalog/controller/extension/payment/mundipagg.php
  catalog/view/theme/default/scripts/mundipagg/mundipagg-checkout.js
  catalog/view/theme/default/scripts/mundipagg/transparent.js
  catalog/view/theme/default/template/extension/payment/mundipagg/credit_card/saved_select.twig
Labels: Feature

#125 Checkout validation
  catalog/controller/extension/payment/mundipagg.php
  catalog/view/theme/default/scripts/mundipagg/mundipagg-form-validation.js
  catalog/view/theme/default/template/extension/payment/mundipagg/credit_card/credit_card.twig
  catalog/view/theme/default/template/extension/payment/mundipagg/credit_card/order_amount_input.twig
  catalog/view/theme/default/template/extension/payment/mundipagg/credit_card/saved_select.twig
  catalog/view/theme/default/template/extension/payment/mundipagg/mundipagg.twig
  system/library/mundipagg/src/Controller/TwoCreditCards.php
  system/library/mundipagg/src/Model/Order.php
Labels: Feature

#126 Two creditcards are always saved
  system/library/mundipagg/src/Controller/TwoCreditCards.php
Labels: Bug

#127 Fixed sensitive card info are sent to backend and other minor bugs.
  catalog/controller/extension/payment/mundipagg.php
  catalog/view/theme/default/scripts/mundipagg/mundipagg-form-validation.js
  catalog/view/theme/default/template/extension/payment/mundipagg/boleto_credit_card.twig
  catalog/view/theme/default/template/extension/payment/mundipagg/credit_card/order_amount_input.twig
Labels: Bug

#129 Round interest value on installments
  system/library/mundipagg/src/Model/Installments.php
Labels: Bug

#130 Round installment tax value and fix first installment with interest skip
  system/library/mundipagg/src/Model/Installments.php
Labels: Bug

#139 Fix installments count on new card
  catalog/controller/extension/payment/mundipagg.php
Labels: Bug

#141 Fix Not focusable form control / add pull request template
  .github/PULL_REQUEST_TEMPLATE.md
  catalog/model/extension/payment/mundipagg_boleto_link.php
  catalog/view/theme/default/template/extension/payment/mundipagg/credit_card/order_amount_input.twig
Labels: Bug, enhancement

#145 #111 Fix empty order status
  catalog/controller/extension/payment/mundipagg.php
  catalog/language/en-gb/extension/payment/mundipagg.php
  catalog/language/pt-br/extension/payment/mundipagg.php
  system/library/mundipagg/src/Order.php
Labels: Bug, Ready

#146 #112 Fix mundipagg M button
  admin/controller/extension/payment/mundipagg_events.php
  admin/view/template/extension/payment/mundipagg/order_actions.twig
  system/library/mundipagg/composer.lock
Labels: Bug, Ready

#147 #114 Move anti fraud settings to its own controller
  system/library/mundipagg/src/Controller/Settings.php
  system/library/mundipagg/src/Order.php
  system/library/mundipagg/src/Settings/AntiFraud.php
  system/library/mundipagg/src/Settings/General.php
Labels: Bug, Ready
