Repository mundipagg/opencart, pull requests merged in 2018-08, with the labels that each got.

#178 Plans CRUD - C
  admin/controller/extension/payment/mundipagg.php
  admin/language/en-gb/extension/payment/mundipagg.php
  admin/language/pt-br/extension/payment/mundipagg.php
  admin/model/extension/payment/mundipagg.php
  admin/view/script/mundipagg/MundipaggLoader.js
  admin/view/script/mundipagg/OpencartMundipaggLoader.js
  admin/view/script/mundipagg/lib/jquery-ui.min.js
  admin/view/script/mundipagg/recurrence/OpencartRecurrencyCreationFormModel.js
  admin/view/script/mundipagg/recurrence/PlansCreationController.js
  admin/view/stylesheet/mundipagg/lib/jquery-ui.min.css
  admin/view/template/extension/payment/mundipagg/recurrence/creationScripts.twig
  admin/view/template/extension/payment/mundipagg/recurrence/plans/productFormTabContent.twig
  admin/view/template/extension/payment/mundipagg/recurrence/templates/form_base.twig
  admin/view/template/extension/payment/mundipagg/recurrence/templates/form_plan.twig
  admin/view/template/extension/payment/mundipagg/recurrence/templates/panelPlanFrequency.twig
  docs/ERDiagram.mwb
  docs/diagrams.mdj
  system/library/mundipagg/src/Aggregates/IAggregateRoot.php
  system/library/mundipagg/src/Aggregates/RecurrencyProduct/RecurrencyProductRoot.php
  system/library/mundipagg/src/Aggregates/RecurrencyProduct/RecurrencySubproductValueObject.php
  system/library/mundipagg/src/Aggregates/Template/TemplateRoot.php
  system/library/mundipagg/src/Controller/Events.php
  system/library/mundipagg/src/Controller/Location.php
  system/library/mundipagg/src/Controller/Recurrence/Plans.php
  system/library/mundipagg/src/Controller/Recurrence/Templates.php
  system/library/mundipagg/src/Factories/RecurrencyProductRootFactory.php
  system/library/mundipagg/src/Factories/RecurrencySubproductValueObjectFactory.php
  system/library/mundipagg/src/Factories/TemplateEntityFactory.php
  system/library/mundipagg/src/Factories/TemplateRootFactory.php
  system/library/mundipagg/src/Repositories/Bridges/OpencartDatabaseBridge.php
  system/library/mundipagg/src/Repositories/RecurrencyProductRepository.php
Labels: Feature, In development

#179 Plans CRUD - D
  admin/controller/extension/payment/mundipagg.php
  admin/model/extension/payment/mundipagg.php
  system/library/mundipagg/src/Aggregates/RecurrencyProduct/RecurrencyProductRoot.php
  system/library/mundipagg/src/Controller/Events.php
  system/library/mundipagg/src/Controller/Recurrence/Plans.php
  system/library/mundipagg/src/Factories/RecurrencyProductRootFactory.php
  system/library/mundipagg/src/Repositories/RecurrencyProductRepository.php
Labels: Feature, In development

#180 Create checksum validate, log download and order info
  catalog/controller/extension/payment/mundipagg_maintenance.php
  integrityDeploy.php
  modman
  system/library/mundipagg/src/Helper/OpencartOrderInfo.php
  system/library/mundipagg/src/Helper/OpencartSystemInfo.php
  system/library/mundipagg/src/Integrity/AbstractOrderInfo.php
  system/library/mundipagg/src/Integrity/FileCompactor.php
  system/library/mundipagg/src/Integrity/IntegrityController.php
  system/library/mundipagg/src/Integrity/IntegrityEngine.php
  system/library/mundipagg/src/Integrity/IntegrityException.php
  system/library/mundipagg/src/Integrity/IntegrityViewer.php
  system/library/mundipagg/src/Integrity/OrderInfoInterface.php
  system/library/mundipagg/src/Integrity/SystemInfoInterface.php
  system/library/mundipagg/src/Integrity/integrityCheck
  system/library/mundipagg/src/Integrity/modman
Labels: Feature, Ready

#181 Plans CRUD - R
  .circleci/config.yml
  .circleci/data/opencart_module_install.sql
  admin/model/extension/payment/mundipagg.php
  admin/model/extension/payment/mundipagg_product.php
  admin/view/template/extension/payment/mundipagg/product_actions.twig
  integrityDeploy.php
  modman
  system/library/mundipagg/src/Controller/Events.php
  system/library/mundipagg/src/Helper/OpencartSystemInfo.php
  system/library/mundipagg/src/Integrity/integrityCheck
  system/library/mundipagg/src/Integrity/modman
Labels: Feature, In development

#182 Plans CRUD - U
  system/library/mundipagg/src/Controller/Events.php
  system/library/mundipagg/src/Controller/Recurrence/Plans.php
  system/library/mundipagg/src/Factories/TemplateEntityFactory.php
  system/library/mundipagg/src/Integrity/integrityCheck
Labels: Feature, Ready

#183 Add Crook to check pushing
  composer.json
  composer.lock
  crook.json
  integrityCheck.php
  integrityPrePushCheck.sh
  system/library/mundipagg/src/Factories/RecurrencyProductRootFactory.php
  system/library/mundipagg/src/Integrity/integrityCheck
  theHook
Labels: Feature, Ready

#184 Fix configuration select in plan creation page
  admin/view/template/extension/payment/mundipagg/recurrence/plans/productFormTabContent.twig
  admin/view/template/extension/payment/mundipagg/recurrence/templates/panelPlanFrequency.twig
  admin/view/template/extension/payment/mundipagg/recurrence/templates/panelSingleFrequency.twig
  composer.lock
  crook.json
  system/library/mundipagg/composer.lock
  system/library/mundipagg/src/Integrity/integrityCheck
Labels: Bug, Ready
