Repository mundipagg/opencart, pull requests merged in 2018-07, with the labels that each got.

#170 Plans and Subscriptions Template CRUD - CREATE
  admin/model/extension/payment/mundipagg.php
  admin/view/script/mundipagg/recurrence.js
  admin/view/template/extension/payment/mundipagg/recurrence/templates/create.twig
  admin/view/template/extension/payment/mundipagg/recurrence/templates/form_base.twig
  admin/view/template/extension/payment/mundipagg/recurrence/templates/form_single.twig
  admin/view/template/extension/payment/mundipagg/recurrence/templates/panelPlanFrequency.twig
  admin/view/template/extension/payment/mundipagg/recurrence/templates/panelSingleFrequency.twig
  docs/ERDiagram.mwb
  docs/diagrams.mdj
  system/library/mundipagg/src/Aggregates/Template/DueValueObject.php
  system/library/mundipagg/src/Aggregates/Template/RepetitionValueObject.php
  system/library/mundipagg/src/Aggregates/Template/TemplateEntity.php
  system/library/mundipagg/src/Aggregates/Template/TemplateRoot.php
  system/library/mundipagg/src/Controller/Recurrence/Templates.php
  system/library/mundipagg/src/Factories/TemplateEntityFactory.php
  system/library/mundipagg/src/Factories/TemplateRootFactory.php
  system/library/mundipagg/src/Repositories/AbstractRep.php
  system/library/mundipagg/src/Repositories/TemplateRepository.php
Labels: Feature, In development

#171 Plans and Subscriptions Template CRUD - READ
  admin/model/extension/payment/mundipagg.php
  admin/view/script/mundipagg/recurrence.js
  admin/view/template/extension/payment/mundipagg/recurrence/templates/base.twig
  admin/view/template/extension/payment/mundipagg/recurrence/templates/create.twig
  admin/view/template/extension/payment/mundipagg/recurrence/templates/form_base.twig
  admin/view/template/extension/payment/mundipagg/recurrence/templates/panelPlanFrequency.twig
  admin/view/template/extension/payment/mundipagg/recurrence/templates/panelSingleFrequency.twig
  docs/ERDiagram.mwb
  docs/diagrams.mdj
  system/library/mundipagg/src/Aggregates/Template/DueValueObject.php
  system/library/mundipagg/src/Aggregates/Template/RepetitionValueObject.php
  system/library/mundipagg/src/Aggregates/Template/TemplateEntity.php
  system/library/mundipagg/src/Aggregates/Template/TemplateRoot.php
  system/library/mundipagg/src/Controller/Recurrence/Templates.php
  system/library/mundipagg/src/Factories/TemplateEntityFactory.php
  system/library/mundipagg/src/Factories/TemplateRootFactory.php
  system/library/mundipagg/src/Repositories/TemplateRepository.php
Labels: Feature, In development

#172 Plans and Subscriptions Template CRUD - UPDATE
  admin/view/template/extension/payment/mundipagg/recurrence/templates/base.twig
  admin/view/template/extension/payment/mundipagg/recurrence/templates/create.twig
  admin/view/template/extension/payment/mundipagg/recurrence/templates/form_base.twig
  admin/view/template/extension/payment/mundipagg/recurrence/templates/form_plan.twig
  admin/view/template/extension/payment/mundipagg/recurrence/templates/form_single.twig
  admin/view/template/extension/payment/mundipagg/recurrence/templates/panelPlanFrequency.twig
  admin/view/template/extension/payment/mundipagg/recurrence/templates/panelSingleFrequency.twig
  docs/diagrams.mdj
  system/library/mundipagg/src/Aggregates/Template/TemplateEntity.php
  system/library/mundipagg/src/Aggregates/Template/TemplateRoot.php
  system/library/mundipagg/src/Controller/Recurrence/Templates.php
  system/library/mundipagg/src/Repositories/AbstractRep.php
  system/library/mundipagg/src/Repositories/TemplateRepository.php
Labels: Feature, In development

#173 Plans and Subscriptions Template CRUD - DELETE
  admin/model/extension/payment/mundipagg.php
  admin/view/template/extension/payment/mundipagg/recurrence/templates/base.twig
  admin/view/template/extension/payment/mundipagg/recurrence/templates/form_base.twig
  docs/ERDiagram.mwb
  docs/diagrams.mdj
  system/library/mundipagg/src/Aggregates/IAGGRoot.php
  system/library/mundipagg/src/Aggregates/Template/TemplateRoot.php
  system/library/mundipagg/src/Controller/Recurrence/Templates.php
  system/library/mundipagg/src/Repositories/AbstractRep.php
  system/library/mundipagg/src/Repositories/TemplateRepository.php
Labels: Feature, In development

#175 Add an abstraction layer to database operations
  admin/view/template/extension/payment/mundipagg/recurrence/plans/productFormTabContent.twig
  docs/diagrams.mdj
  system/library/mundipagg/src/Controller/Events.php
  system/library/mundipagg/src/Controller/Recurrence/Templates.php
  system/library/mundipagg/src/Repositories/AbstractRep.php
  system/library/mundipagg/src/Repositories/Bridges/AbstractDatabaseBridge.php
  system/library/mundipagg/src/Repositories/Bridges/OpencartDatabaseBridge.php
  system/library/mundipagg/src/Repositories/TemplateRepository.php
Labels: Feature, Ready

#176 Fix guest orders
  catalog/controller/extension/payment/mundipagg.php
Labels: Bug, Ready

#177 300 fix cancel and capture by module
  admin/controller/extension/payment/mundipagg.php
  admin/language/en-gb/extension/payment/mundipagg.php
  admin/view/image/mundipagg/mundipagg-mini-white.png
  admin/view/script/mundipagg/cancel_capture.js
  admin/view/stylesheet/mundipagg/mundipagg.css
  admin/view/template/extension/payment/mundipagg/cancel_capture_modal.twig
  admin/view/template/extension/payment/mundipagg/loader.twig
  admin/view/template/extension/payment/mundipagg/order_actions.twig
  admin/view/template/extension/payment/mundipagg_confirmUpdateCharge.twig
  admin/view/template/extension/payment/mundipagg_previewChangeCharge.twig
  system/library/mundipagg/src/Controller/Charge.php
  system/library/mundipagg/src/Controller/Charges.php
  system/library/mundipagg/src/Log.php
  system/library/mundipagg/src/LogMessages.php
  system/library/mundipagg/src/Model/Charge.php
  system/library/mundipagg/src/Model/Order.php
  system/library/mundipagg/src/Model/WebHook.php
  system/library/mundipagg/src/Order.php
Labels: Bug
