Repository mundipagg/opencart, pull requests merged in 2018-06, with the labels that each got.

#158 Fix undefined variables on cards saved
  catalog/controller/extension/payment/mundipagg.php
  catalog/view/theme/default/scripts/mundipagg/mundipagg-form-validation.js
  catalog/view/theme/default/template/extension/payment/mundipagg/multi_buyer_form.twig
  system/library/mundipagg/src/Controller/TwoCreditCards.php
  system/library/mundipagg/src/MultiBuyer.php
Labels: Bug, Ready

#162 Create Mundipagg menu using events
  admin/controller/extension/payment/mundipagg.php
  admin/language/en-gb/extension/payment/mundipagg.php
  admin/language/pt-br/extension/payment/mundipagg.php
  admin/model/extension/payment/mundipagg.php
  admin/view/image/mundipagg/mundipagg-mini.png
  admin/view/template/extension/payment/mundipagg/menu/mundipagg.twig
  composer.lock
  install.xml
  system/library/mundipagg/src/Controller/Events.php
  system/library/mundipagg/src/Helper/AdminMenu.php
  system/library/mundipagg/src/Helper/Common.php
Labels: Feature, Ready

#164 Initial recurrence screens
  README.md
  admin/controller/extension/payment/mundipagg.php
  admin/language/en-gb/extension/payment/mundipagg.php
  admin/language/pt-br/extension/payment/mundipagg.php
  admin/model/extension/payment/mundipagg.php
  admin/view/stylesheet/mundipagg/mundipagg.css
  admin/view/template/extension/payment/mundipagg/recurrence/actions.twig
  admin/view/template/extension/payment/mundipagg/recurrence/breadcrumb.twig
  admin/view/template/extension/payment/mundipagg/recurrence/pagination.twig
  admin/view/template/extension/payment/mundipagg/recurrence/panelIcons.twig
  admin/view/template/extension/payment/mundipagg/recurrence/plans/base.twig
  admin/view/template/extension/payment/mundipagg/recurrence/plans/grid.twig
  admin/view/template/extension/payment/mundipagg/recurrence/plans/list.twig
  admin/view/template/extension/payment/mundipagg/recurrence/plans/productFormTabContent.twig
  admin/view/template/extension/payment/mundipagg/recurrence/plans/productFormTabHeader.twig
  admin/view/template/extension/payment/mundipagg/recurrence/subscriptions/base.twig
  admin/view/template/extension/payment/mundipagg/recurrence/subscriptions/create.twig
  modman
  system/library/mundipagg/composer.lock
  system/library/mundipagg/src/Controller/Charges.php
  system/library/mundipagg/src/Controller/Events.php
  system/library/mundipagg/src/Controller/Recurrence/Plans.php
  system/library/mundipagg/src/Controller/Recurrence/Recurrence.php
  system/library/mundipagg/src/Controller/Recurrence/Subscriptions.php
  system/library/mundipagg/src/Helper/Common.php
  system/library/mundipagg/src/Helper/ProductPageChanges.php
  system/library/mundipagg/src/Order.php
Labels: Feature, In development

#166 Change API url
  tests/catalog/MundipaggTest.php
Labels: Bug, Ready

#167 Fix NaN on autobalance amount
  catalog/controller/extension/payment/mundipagg.php
  catalog/model/extension/payment/mundipagg_credit_card.php
  catalog/view/theme/default/scripts/mundipagg/mundipagg-form-validation.js
  catalog/view/theme/default/template/extension/payment/mundipagg/credit_card/order_amount_input.twig
Labels: Bug, Ready

#168 Implement multibuyer to boleto
  catalog/controller/extension/payment/mundipagg.php
  catalog/view/theme/default/template/extension/payment/mundipagg/boleto/base.twig
  catalog/view/theme/default/template/extension/payment/mundipagg/boleto/submit.twig
  catalog/view/theme/default/template/extension/payment/mundipagg/mundipagg.twig
  catalog/view/theme/default/template/extension/payment/mundipagg/success/order_info.twig
  system/library/mundipagg/src/Order.php
Labels: Feature, Ready
