Repository mundipagg/opencart, pull requests merged in 2018-04, with the labels that each got.

#150 Remove mundipagg_events
  admin/controller/extension/payment/mundipagg.php
  admin/model/extension/payment/mundipagg.php
  system/library/mundipagg/src/Controller/Events.php
Labels: Bug, Ready

#153 Fix installments update on creditcard number input.
  catalog/view/theme/default/scripts/mundipagg/mundipagg-form-validation.js
  catalog/view/theme/default/template/extension/payment/mundipagg/credit_card/credit_card.twig
Labels: Bug, Ready

#152 Show order info on my account order review
  admin/model/extension/payment/mundipagg.php
  catalog/controller/extension/payment/mundipagg.php
  catalog/controller/extension/payment/mundipagg_events.php
  catalog/language/en-gb/extension/payment/mundipagg.php
  catalog/language/pt-br/extension/payment/mundipagg.php
  catalog/model/extension/payment/mundipagg_order_boleto_info.php
  catalog/model/extension/payment/mundipagg_order_creditcard_info.php
  catalog/view/theme/default/template/extension/payment/mundipagg/account/order_info.twig
  system/library/mundipagg/src/Controller/TwoCreditCards.php
  system/library/mundipagg/src/Model/Order.php
Labels: Feature, Ready

#154 Add CI with CircleCI and Rancher
  .circleci/config.yml
  .circleci/data/Dockerfile
  .circleci/data/opencart_module_install.sql
  .circleci/data/wait-for-mysql.sh
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
  PULLREQUEST-TEMPLATE.md
  README.md
  getOrderTotals
Labels: CI, Feature, Ready, enhancement
