Repository mundipagg/opencart, pull requests merged in 2018-05, with the labels that each got.

#157 Fix validations require on multi buyer feature
  catalog/controller/extension/payment/mundipagg.php
  catalog/view/theme/default/scripts/mundipagg/mundipagg-form-validation.js
  catalog/view/theme/default/template/extension/payment/mundipagg/multi_buyer_form.twig
Labels: Bug, Ready

#159 Functional Test on CI
  .circleci/config.yml
  behat.yml
  features/bootstrap/FeatureContext.php
  features/test.feature
Labels: CI, Feature, Ready

#161 Improve charges details screen
  admin/controller/extension/payment/mundipagg.php
  admin/view/template/extension/payment/mundipagg_confirmUpdateCharge.twig
  admin/view/template/extension/payment/mundipagg_previewChangeCharge.twig
Labels: Ready
